DB_TYPE = "postgresql"
DB_HOST = "db.qgchwhriueqriqrcepqw.supabase.co"
DB_PORT = "5432"
DB_NAME = "postgres"
DB_USER = "postgres"
DB_PASSWORD = "N@mikaz312"
EXCHANGE_CRYPTO = "binance"
TIMEFRAME = "1h"
