# PASTIKAN FORMAT INI - HANYA INDIVIDUAL PARAMETERS
DB_HOST = "aws-1-ap-southeast-1.pooler.supabase.com"
DB_PORT = 5432
DB_NAME = "postgres"
DB_USER = "postgres.qgchwhriueqriqrcepqw"
DB_PASSWORD = "N@mikaz312"
ALPHA_VANTAGE_KEY=Q6Z2UVHA92P79R3T

# Trading config
EXCHANGE_CRYPTO = "binance"
TIMEFRAME = "1h"
ATR_MULTIPLIER = 1.0
ENTRY_RANGE_PCT = 0.02
ANALYSIS_COINS_LIMIT = 50
OHLCV_LIMIT = 200
MIN_SCORE_LONG = 5
MIN_SCORE_SHORT = 2
SOLANA_RPC = "https://api.mainnet-beta.solana.com"
